### registration
POST http://localhost:8080/api/v1/auth/registration
Content-Type: application/json
Accept-Language: en

{
  "fullName": "Ali Aliyev",
  "email": "codeuz91@gmail.com",
  "password": "1234"
}

### login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "hojiakbarandaqulov5@gmail.com",
  "password": "1234"
}

### verification
GET http://localhost:8080/api/v1/auth/verification/dfd14ba1-4cb0-491f-9e7e-f1612712ec7f?lang=uz
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiJkZmQxNGJhMS00Y2IwLTQ5MWYtOWU3ZS1mMTYxMjcxMmVjN2YiLCJpYXQiOjE3NDIwOTg2NjAsImV4cCI6MTc0MjQ0NDI2MH0.r2XFlWW_MjLJ0qxSU70VEvNqF1HMlbKwbzpwQ__7mtjoY-U_ZZEfnGMKNEgM_tYLzzF27dtbN1bdc1t-I3knXQ


### resent email
POST http://localhost:8080/api/v1/auth/registration/reset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiJkZmQxNGJhMS00Y2IwLTQ5MWYtOWU3ZS1mMTYxMjcxMmVjN2YiLCJpYXQiOjE3NDIwOTg2NjAsImV4cCI6MTc0MjQ0NDI2MH0.r2XFlWW_MjLJ0qxSU70VEvNqF1HMlbKwbzpwQ__7mtjoY-U_ZZEfnGMKNEgM_tYLzzF27dtbN1bdc1t-I3knXQ

{
  "email": "codeuz91@gmail.com"
}

### update password
PUT http://localhost:8080/api/v1/auth/password/update
Content-Type: application/json

{
  "username": "hojiakbarandaqulov5@gmail.com",
  "confirmPassword": "2241",
  "newPassword": "12345"
}
